# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
a1=np.random.random((3,3,3))
print(a1)

[[[0.85028662 0.0241731  0.37450663]
  [0.47438064 0.96674491 0.60595928]
  [0.71251552 0.52331126 0.41781258]]

 [[0.61176333 0.72060542 0.32305626]
  [0.28596134 0.0202723  0.31585512]
  [0.04068294 0.47979715 0.30697042]]

 [[0.84788354 0.77607401 0.19671569]
  [0.17266555 0.68697034 0.7438146 ]
  [0.94050032 0.20412055 0.54783674]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
x = np.diag(1+np.arange(4), k = -1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
x1 = np.zeros((8,8),dtype=int)
x1[1::2,::2] = 1
x1[::2,1::2] = 1
print(x1)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [4]:
arr=np.random.randint(130,size=(5,5))
print('original array:')
print(arr)
new_arr=(arr-arr.min())/(arr.max()-arr.min())
print('Normalized Array:')
print(new_arr)

original array:
[[ 23   5  78  39  96]
 [128  43  48  26  17]
 [ 31 109  51 126 126]
 [126  40  47  31  72]
 [ 50  25 109 109 115]]
Normalized Array:
[[0.14634146 0.         0.59349593 0.27642276 0.7398374 ]
 [1.         0.30894309 0.3495935  0.17073171 0.09756098]
 [0.21138211 0.84552846 0.37398374 0.98373984 0.98373984]
 [0.98373984 0.28455285 0.34146341 0.21138211 0.54471545]
 [0.36585366 0.16260163 0.84552846 0.84552846 0.89430894]]


# 5.  How to find common values between two arrays?

In [5]:
a3=np.array([10,20,30,40,50])
a4=np.array([20,25,40,45])
a5=np.intersect1d(a3,a4)
print('Common Values: ',a5)

Common Values:  [20 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [6]:
yesterday=np.datetime64('today','D') - np.timedelta64(1,'D')
print('Yestraday: ',yesterday)
today= np.datetime64('today','D')
print('Today: ',today)
tomorrow=np.datetime64('today','D') + np.timedelta64(1,'D')
print('Tomorrow: ',tomorrow)

Yestraday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [7]:
A=np.array([[2,3,4],[6,4,8],[10,9,7]])
print('First Array:\n',A)
B=np.array([[2,3,4],[6,4,8]])
print('Second Array:\n',B)
np.array_equal(A,B)

First Array:
 [[ 2  3  4]
 [ 6  4  8]
 [10  9  7]]
Second Array:
 [[2 3 4]
 [6 4 8]]


False

# 8.Create random vector of size 10 and replace the maximum value by 0 

In [8]:
arr1=np.random.randint(30,size=10)
print('original Array: ',arr1)
arr1[arr1.argmax()]=0
print('New array: ',arr1)

original Array:  [27 23 28 13 28 19 26  5 14  7]
New array:  [27 23  0 13 28 19 26  5 14  7]


# 9. How to print all the values of an array?

In [9]:
arr2=np.array([10,14,17,20,24])
for i in arr2:
    print(i)

10
14
17
20
24


# 10.Subtract the mean of each row of a matrix

In [11]:
arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
mean_arr=np.mean(arr3,axis=1)
x=np.array([mean_arr]).T
new=arr3-x
print('Mean array:\n',x)
print('After subtracting mean array:\n',new)

Mean array:
 [[2.]
 [5.]
 [8.]]
After subtracting mean array:
 [[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [12]:
c=np.array([10,15,20,25,35,38,42,56,60,70])
index=np.random.randint(len(c),size=4)
print('Given Vector: ',c)
print('index vector: ',index)
l=[]
for i in index:
    if i not in l:
        l.append(i)
new_in=np.array(l)
print('New index vector: ',new_in)
for i in new_in:
    c[i]=c[i]+1
print('new vector: ',c)

Given Vector:  [10 15 20 25 35 38 42 56 60 70]
index vector:  [4 7 3 2]
New index vector:  [4 7 3 2]
new vector:  [10 15 21 26 36 38 42 57 60 70]


# 12.How to get the diagonal of a dot product?

In [13]:
ar1=np.array([[1,2,3],[2,3,1],[5,6,7]])
ar2=np.array([[3,4,5],[2,4,3],[9,8,3]])
dp=np.dot(ar1,ar2)
print('Dot Product array:\n',dp)
diagonal=np.diag(dp)
print('Diagonal: ',diagonal)

Dot Product array:
 [[ 34  36  20]
 [ 21  28  22]
 [ 90 100  64]]
Diagonal:  [34 28 64]


# 13.How to find the most frequent value in an array?

In [14]:
d=np.array([10,20,30,30,20,56,45,30,32,10,32])
print('Original array:\n',d)
print('Most frequent value:')
print(np.bincount(d).argmax())

Original array:
 [10 20 30 30 20 56 45 30 32 10 32]
Most frequent value:
30


# 14.How to get the n largest values of an array

In [16]:
x = np.arange(20)
print("Original array:\n",x)
np.random.shuffle(x)
n = 3
print ('n largest values in array:\n',x[np.argsort(x)[-n:]])

Original array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
n largest values in array:
 [17 18 19]


# 15.How to create a record array from a regular array?

In [17]:
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result)

[(1, 'Red', 12.2) (2, 'Green', 15. ) (3, 'White', 20. )
 (4, 'Orange', 40. )]
